using System;
using System.Collections.Generic;
using System.Text;

namespace PrincipleStudios.OpenApi.Transformations
{
    public static class HttpStatusCodes
    {
        public static readonly IReadOnlyDictionary<int, string> StatusCodeNames = new Dictionary<int, string>
        {
            [100] = "Continue",
            [101] = "SwitchingProtocols",
            [102] = "Processing",
            [103] = "EarlyHints",
            [200] = "OK",
            [201] = "Created",
            [202] = "Accepted",
            [203] = "NonAuthoritativeInformation",
            [204] = "NoContent",
            [205] = "ResetContent",
            [206] = "PartialContent",
            [207] = "MultiStatus",
            [208] = "AlreadyReported",
            [226] = "IMUsed",
            [300] = "Ambiguous",
            [301] = "Moved",
            [302] = "Redirect",
            [303] = "RedirectMethod",
            [304] = "NotModified",
            [305] = "UseProxy",
            [306] = "Unused",
            [307] = "TemporaryRedirect",
            [308] = "PermanentRedirect",
            [400] = "BadRequest",
            [401] = "Unauthorized",
            [402] = "PaymentRequired",
            [403] = "Forbidden",
            [404] = "NotFound",
            [405] = "MethodNotAllowed",
            [406] = "NotAcceptable",
            [407] = "ProxyAuthenticationRequired",
            [408] = "RequestTimeout",
            [409] = "Conflict",
            [410] = "Gone",
            [411] = "LengthRequired",
            [412] = "PreconditionFailed",
            [413] = "RequestEntityTooLarge",
            [414] = "RequestUriTooLong",
            [415] = "UnsupportedMediaType",
            [416] = "RequestedRangeNotSatisfiable",
            [417] = "ExpectationFailed",
            [418] = "IAmATeapot",
            [421] = "MisdirectedRequest",
            [422] = "UnprocessableEntity",
            [423] = "Locked",
            [424] = "FailedDependency",
            [426] = "UpgradeRequired",
            [428] = "PreconditionRequired",
            [429] = "TooManyRequests",
            [431] = "RequestHeaderFieldsTooLarge",
            [451] = "UnavailableForLegalReasons",
            [500] = "InternalServerError",
            [501] = "NotImplemented",
            [502] = "BadGateway",
            [503] = "ServiceUnavailable",
            [504] = "GatewayTimeout",
            [505] = "HttpVersionNotSupported",
            [506] = "VariantAlsoNegotiates",
            [507] = "InsufficientStorage",
            [508] = "LoopDetected",
            [510] = "NotExtended",
            [511] = "NetworkAuthenticationRequired",
        };
    }
}
