openapi: "3.0.3"
info:
  version: 1.0.0
  title: OAuth Scopes Sample
  description: A sample API that uses oauth scopes
paths:
  /api/info:
    get:
      operationId: getInfo
      parameters:
        - name: data
          in: query
          description: base-64 encoded data
          required: false
          schema:
            type: string
            format: byte
      responses:
        '200':
          description: Sample Response
          content:
            application/json:
              schema:
                type: string
    x-dotnet-mvc-server-controller: Information