openapi: "3.0.3"
info:
  version: 1.0.0
  title: Nullable vs Optional
  description: A sample API that demonstrates the difference between nullable and optional properties
paths:
  /search:
    post:
      operationId: search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                department:
                  type: string
      responses:
        '200':
          description: List of results
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - id
                    - name
                    - department
                  properties:
                    id: { type: string }
                    name: { type: string }
                    department: { type: string, nullable: true }
