openapi: "3.0.3"
info:
  version: 1.0.0
  title: OAuth Scopes Sample
  description: A sample API that uses oauth scopes
paths:
  /info:
    get:
      operationId: getInfo
      security:
        - {}
        - ApiKeyAuth: []
      parameters:
        - name: data
          in: query
          description: base-64 encoded data
          required: false
          style: form
          schema:
            type: string
            format: byte
      responses:
        '200':
          description: Sample Response
          content:
            application/json:
              schema:
                type: string
  /address:
    get:
      operationId: getAddress
      security:
        - ApiKeyAuth: []
        - OAuth2:
          - read
          - write
      responses:
        '200':
          description: Sample Response
          content:
            application/json:
              schema:
                type: string
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants access to admin operations