openapi: "3.0.3"
info:
  version: 1.0.0
  title: OAuth Scopes Sample
  description: A sample API that uses oauth scopes
paths:
  /oauth/info:
    get:
      operationId: getInfo
      security:
        - {}
        - ApiKeyAuth: []
      responses:
        '200':
          description: Sample Response
          content:
            application/json:
              schema:
                type: string
  /oauth/address:
    get:
      operationId: getAddress
      security:
        - ApiKeyAuth: []
        - OAuth2:
          - read:user
          - user:email
      responses:
        '200':
          description: Sample Response
          content:
            application/json:
              schema:
                type: string
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants access to admin operations
