openapi: '3.0.2'
info:
  title: OneOf Example
  version: '1.0'

components:
  schemas:
    Dog:
      type: object
      properties:
        bark:
          type: boolean
        breed:
          type: string
    Cat:
      type: object
      properties:
        hunts:
          type: boolean
        age:
          type: integer
    Pet:
      oneOf:
      - $ref: '#/components/schemas/Cat'
      - $ref: '#/components/schemas/Dog'
paths:
  /pets:
    get:
      operationId: getRandomPet
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
  /id:
    get:
      operationId: getRandomId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                - type: integer
                - type: string
                  format: uuid