name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
            dotnet-version: 6.0.x
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      working-directory: ./lib/PrincipleStudios.OpenApiCodegen.Server.Mvc.Test
      run: dotnet build --no-restore --configuration Release
    - name: Test
      working-directory: ./lib/PrincipleStudios.OpenApiCodegen.Server.Mvc.Test
      run: dotnet test --no-build --verbosity normal --configuration Release --collect:"XPlat Code Coverage"
    ## The code coverage action works, but doesn't do much.
    # - name: Record code coverage
    #   uses: 5monkeys/cobertura-action@master
    #   with:
    #     path: lib/PrincipleStudios.OpenApiCodegen.Server.Mvc.Test/out/TestResults/*/coverage.cobertura.xml
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     minimum_coverage: 90
    #     fail_below_threshold: false
    - name: Build Package
      working-directory: ./generators/dotnetcore-server-interfaces/PrincipleStudios.OpenApiCodegen.Server.Mvc.MsBuild
      run: dotnet pack --no-restore --configuration Release -o out
    - name: Publish Nuget to GitHub registry if new version number
      run: dotnet nuget push ./generators/dotnetcore-server-interfaces/PrincipleStudios.OpenApiCodegen.Server.Mvc.MsBuild/out/*.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/$GITHUB_REPOSITORY_OWNER/index.json --skip-duplicate --no-symbols
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
