name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
            dotnet-version: 6.0.x
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      working-directory: ./lib/PrincipleStudios.OpenApiCodegen.Server.Mvc.Test
      run: dotnet build --no-restore --configuration Release
    - name: Test
      working-directory: ./lib/PrincipleStudios.OpenApiCodegen.Server.Mvc.Test
      run: dotnet test --no-build --verbosity normal --configuration Release
